/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.softdirex.sdxkeygen.view;

import cl.softdirex.sdxkeygen.utils.Icons;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;

/**
 *
 * @author Lenovo G470
 */
public class Window extends javax.swing.JFrame {

    String version = "v1.0.0";
    String title = "KeyGen ";
    String projectName = title+" "+version;
    public static final String ICON_LOGO = "/images/icon.png";
    /**
     * Creates new form Acceso
     */
    
    public Window() {
        initComponents();
        txtProjectName.setHorizontalAlignment(SwingConstants.CENTER);
        txtVersion.setHorizontalAlignment(SwingConstants.CENTER);
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ICON_LOGO));
        setIconImage(icon);
        this.setTitle(projectName);
        this.txtProjectName.setText(projectName);
        this.txtVersion.setText(version);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnter = new javax.swing.JLabel();
        txtVersion = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        txtPass1 = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        txtProjectName1 = new javax.swing.JLabel();
        lblLicencia = new javax.swing.JLabel();
        txtProjectName4 = new javax.swing.JLabel();
        txtProjectName5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Enter_32px.png"))); // NOI18N
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterMouseExited(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        txtVersion.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        txtVersion.setForeground(new java.awt.Color(255, 255, 255));
        txtVersion.setText("version 1.0.0");
        getContentPane().add(txtVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, -1));

        txtProjectName.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        txtProjectName.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectName.setText("Clave");
        getContentPane().add(txtProjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, -1));

        txtUser.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 210, -1));

        txtPass1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPass1.setForeground(new java.awt.Color(51, 51, 51));
        txtPass1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1ActionPerformed(evt);
            }
        });
        txtPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPass1KeyPressed(evt);
            }
        });
        getContentPane().add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 210, -1));

        txtPass2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPass2.setForeground(new java.awt.Color(51, 51, 51));
        txtPass2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        txtPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPass2KeyPressed(evt);
            }
        });
        getContentPane().add(txtPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, -1));

        txtProjectName1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        txtProjectName1.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectName1.setText("Contraseña");
        getContentPane().add(txtProjectName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, -1));

        lblLicencia.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        lblLicencia.setForeground(new java.awt.Color(255, 255, 255));
        lblLicencia.setText("Licencia");
        getContentPane().add(lblLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        txtProjectName4.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        txtProjectName4.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectName4.setText("ProjectName");
        getContentPane().add(txtProjectName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, -1));

        txtProjectName5.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        txtProjectName5.setForeground(new java.awt.Color(255, 255, 255));
        txtProjectName5.setText("Base de datos");
        getContentPane().add(txtProjectName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, -1));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 401, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        
    }//GEN-LAST:event_btnEnterMouseClicked

    private void btnEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseEntered
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getEnteredIcon(btnEnter.getIcon().toString()))));
    }//GEN-LAST:event_btnEnterMouseEntered

    private void btnEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseExited
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icons.getExitedIcon(btnEnter.getIcon().toString()))));
    }//GEN-LAST:event_btnEnterMouseExited

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1ActionPerformed

    private void txtPass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1KeyPressed

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void txtPass2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEnter;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JLabel txtProjectName;
    private javax.swing.JLabel txtProjectName1;
    private javax.swing.JLabel txtProjectName4;
    private javax.swing.JLabel txtProjectName5;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel txtVersion;
    // End of variables declaration//GEN-END:variables
}
